### ISSUE TITLE
About data and pre training model

### ISSUE THREAD

**Issue by BobbyLiukeling** [kochgroup/neural_npfp#1]
Hello, can you upload the supporting data and pre training model, otherwise the experiment will be difficult to reproduce

**Comment by BobbyLiukeling** [comment]
Like NP_ AUX model

**Comment by JanoschMenke** [comment]
Sorry for the long waiting time. I actually never got a notification about the Issue. We are still working things out, with the adequate file hosting. For now if you want to drop me an E-Mail. janosch.menke [at] wwu.de I will send you the neccessary data
